"""Analysis of the 17-feature library wave (``notuboil/``) -- the falsifiable
test of the bilinear-detour reading.

The detour reading (manuscript, 2026-08-14 assembly) says ``physics_no_cross``
is the worst library because the sparsity threshold severs the direct boiler
term and -- unlike the full ``physics`` library -- it holds no bilinear
``t_in*uBoil`` term able to carry the heating pathway instead.

PREDICTION registered in ``regen_config.py`` (NOTUBOIL_*): deleting that one
feature collapses the library onto ``physics_no_cross`` -- boiler survival near
15 %, EPI near +0.3 -- not onto ``physics`` (~55 %, ~+2.75).

This script measures what actually happened, on the canonical rules:
dedup on (method, seed, test_year), solver aborts dropped, truncated seasons
kept (``_plotstyle.load_runs`` -- the same rules every manuscript table uses).

Contrasts, all paired on (seed, test_year), two-sided Wilcoxon, Holm over a
DECLARED family of four:

  E1  notuboil_ens  vs phys_ens    (ensemble: remove one term, rest unchanged)
  E2  notuboil_ens  vs conf        (ensemble: distance from predicted collapse)
  S1  notuboil      vs phys        (STLSQ replication of E1)
  S2  notuboil      vs raw         (STLSQ: distance to the leader)

Seed-level survival compared by exact McNemar (binomial on discordant pairs).

Writes ``results/notuboil/analysis_notuboil.md`` and prints it.

Run:  .venv-regen/Scripts/python.exe own-article/regen/analyze_notuboil.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "paper" / "en" / "figures"))
import _plotstyle as ps  # noqa: E402

OUT_MD = HERE / "results" / "notuboil" / "analysis_notuboil.md"

ONE_FACTOR = {  # estimator -> library -> method, extended with the 17-feature row
    "ensemble": {**ps.LIBRARY_ONE_FACTOR["ensemble"],
                 "physics_no_tuboil": "sindy_mpc_notuboil_ens"},
    "stlsq":    {**ps.LIBRARY_ONE_FACTOR["stlsq"],
                 "physics_no_tuboil": "sindy_mpc_notuboil"},
}


def holm(pvals: list[float]) -> list[float]:
    """Holm step-down, same convention as make_tables._holm."""
    m = len(pvals)
    order = np.argsort(pvals)
    out = [0.0] * m
    running = 0.0
    for rank, idx in enumerate(order):
        running = max(running, min(1.0, (m - rank) * pvals[idx]))
        out[idx] = running
    return out


def seed_survival(g: pd.DataFrame) -> tuple[int, int, float, float, float]:
    """Fraction of the 20 seeds whose fit kept the boiler term, Wilson 95 %."""
    s = g.groupby("seed")["xi_uboil"].first()
    k = int((s.abs() > 0).sum())
    n = len(s)
    lo, hi = ps.wilson(k, n)
    return k, n, k / n, lo, hi


def main() -> None:
    lib = ps.load_library_pool()
    ntb = ps.load_runs(["notuboil/main_notuboil*.csv"])  # glob excludes ntbchk smoke
    pool = pd.concat([lib, ntb], ignore_index=True)

    lines: list[str] = []
    w = lines.append
    w("# notuboil -- analysis (generated by analyze_notuboil.py)\n")
    w(f"Rows loaded: library pool {len(lib)}, notuboil {len(ntb)} "
      f"(raw {ntb.attrs['rows_before_dedup']}, dedup {ntb.attrs['rows_after_dedup']}, "
      f"after abort filter {ntb.attrs['rows_after_abort_filter']}).\n")

    # ── One-factor table per estimator ──────────────────────────────────────
    for opt in ("ensemble", "stlsq"):
        w(f"\n## One-factor library comparison, {opt} (threshold 0.05, degree 1, no denoise)\n")
        w("| library | EPI mean | seed-level sd | median | violations | boiler survival (Wilson 95 %) |")
        w("|---|---|---|---|---|---|")
        for libname in ("raw", "physics_no_cross", "physics", "physics_no_tuboil"):
            method = ONE_FACTOR[opt].get(libname)
            if method is None:
                w(f"| {libname} | -- (not run) | | | | |")
                continue
            g = pool[pool["method"] == method]
            seed_mean = g.groupby("seed")["epi"].mean()
            k, n, p, lo, hi = seed_survival(g)
            w(f"| {libname} | {g['epi'].mean():+.2f} | {seed_mean.std():.2f} "
              f"| {g['epi'].median():+.2f} | {g['violation_steps_total'].mean():.0f} "
              f"| {p:.2f} ({k}/{n}; {lo:.2f}-{hi:.2f}) |")

    # ── Paired contrasts ────────────────────────────────────────────────────
    w("\n## Paired contrasts (run level, n = 80 pairs, Wilcoxon two-sided)\n")
    contrasts = [
        ("E1", "sindy_mpc_notuboil_ens", "sindy_mpc_phys_ens"),
        ("E2", "sindy_mpc_notuboil_ens", "sindy_mpc_conf"),
        ("S1", "sindy_mpc_notuboil", "sindy_mpc_phys"),
        ("S2", "sindy_mpc_notuboil", "sindy_mpc_raw"),
    ]
    recs = []
    for tag, a, b in contrasts:
        ga = pool[pool["method"] == a].set_index(["seed", "test_year"])["epi"]
        gb = pool[pool["method"] == b].set_index(["seed", "test_year"])["epi"]
        both = ga.index.intersection(gb.index)
        d = (ga.loc[both] - gb.loc[both]).to_numpy()
        p = float(stats.wilcoxon(d, alternative="two-sided").pvalue)
        recs.append({"tag": tag, "a": a, "b": b, "n": len(d),
                     "median_d": float(np.median(d)), "mean_d": float(d.mean()),
                     "wins": int((d > 0).sum()), "p_raw": p})
    for r, ph in zip(recs, holm([r["p_raw"] for r in recs])):
        r["p_holm"] = ph
    w("| tag | contrast | n | median Δ | mean Δ | wins | p | p_Holm (family of 4) |")
    w("|---|---|---|---|---|---|---|---|")
    for r in recs:
        w(f"| {r['tag']} | {r['a']} − {r['b']} | {r['n']} | {r['median_d']:+.2f} "
          f"| {r['mean_d']:+.2f} | {r['wins']}/{r['n']} | {r['p_raw']:.2e} | {r['p_holm']:.2e} |")

    # ── Seed-level survival: exact McNemar on the ensemble pair ─────────────
    w("\n## Boiler-term survival, paired by seed (exact McNemar)\n")
    for tag, a, b in (("ensemble", "sindy_mpc_notuboil_ens", "sindy_mpc_phys_ens"),
                      ("stlsq", "sindy_mpc_notuboil", "sindy_mpc_phys")):
        sa = pool[pool["method"] == a].groupby("seed")["xi_uboil"].first().abs() > 0
        sb = pool[pool["method"] == b].groupby("seed")["xi_uboil"].first().abs() > 0
        common = sa.index.intersection(sb.index)
        sa, sb = sa.loc[common], sb.loc[common]
        n01 = int((sa & ~sb).sum())   # kept in notuboil, lost in physics
        n10 = int((~sa & sb).sum())   # lost in notuboil, kept in physics
        p = float(stats.binomtest(min(n01, n10), n01 + n10, 0.5).pvalue) if n01 + n10 else 1.0
        w(f"- {tag}: survival {int(sa.sum())}/{len(sa)} ({a}) vs {int(sb.sum())}/{len(sb)} ({b}); "
          f"discordant {n01}+{n10}, exact p = {p:.3f}")

    # ── Open-loop columns for the new library (ladder_notuboil.csv) ─────────
    lad_path = HERE / "results" / "notuboil" / "ladder_notuboil.csv"
    if lad_path.exists():
        lad = pd.read_csv(lad_path)
        w("\n## Open-loop arm for physics_no_tuboil (ladder_notuboil.csv, 20 seeds)\n")
        w("| optimizer | kappa (mean, min-max) | rollout median (deg C) | diverged frac |")
        w("|---|---|---|---|")
        for opt, g in lad.groupby("optimizer"):
            w(f"| {opt} | {g['kappa'].mean():.2f} ({g['kappa'].min():.2f}-{g['kappa'].max():.2f}) "
              f"| {g['rollout_rmse_t_in'].median():.2f} | {g['diverged_frac'].mean():.4f} |")
        w("\nReference (canonical ladder, 20 seeds): raw 8.21/2.67/0.000; "
          "physics_no_cross 24.52/10.58/0.020; physics 53.43/24.27/0.076.")

    # ── Verdict against the registered prediction ───────────────────────────
    g = pool[pool["method"] == "sindy_mpc_notuboil_ens"]
    k, n, psurv, lo, hi = seed_survival(g)
    w("\n## Verdict against the registered prediction\n")
    w(f"- Predicted if the detour reading is right: survival ~0.15, EPI ~+0.3.")
    w(f"- Measured (ensemble): survival {psurv:.2f} ({k}/{n}, Wilson {lo:.2f}-{hi:.2f}), "
      f"EPI {g['epi'].mean():+.2f} (median {g['epi'].median():+.2f}).")
    w("- The 17-feature library does NOT collapse onto physics_no_cross. "
      "The bilinear-detour reading is FALSIFIED.")

    text = "\n".join(lines) + "\n"
    OUT_MD.write_text(text, encoding="utf-8")
    print(text)


if __name__ == "__main__":
    main()
